# kwargs['SYSTEM_NAME'] = os.getenv('SYSTEM_NAME')
# kwargs['SYSTEM_EMAIL'] = os.getenv('SYSTEM_EMAIL')
# kwargs['SYSTEM_URL'] = os.getenv('SYSTEM_URL')
# kwargs['DOMAIN'] = os.getenv('DOMAIN')
# kwargs['DATE_FORMAT'] = os.getenv('DATE_FORMAT')
# kwargs['TIME_FORMAT'] = os.getenv('TIME_FORMAT')
# kwargs['DATETIME_FORMAT'] = os.getenv('DATETIME_FORMAT')

# kwargs['GOOGLE_ANALYTICS'] = os.getenv('GOOGLE_ANALYTICS')
# kwargs['GITHUB_ACCOUNT'] = os.getenv('GITHUB_ACCOUNT')
# kwargs['TWITTER_ACCOUNT'] = os.getenv('TWITTER_ACCOUNT')
# kwargs['FACEBOOK_ACCOUNT'] = os.getenv('FACEBOOK_ACCOUNT')
# kwargs['FACEBOOK_API_KEY'] = os.getenv('FACEBOOK_API_KEY')
# kwargs['GOOGLE_PLUS_ACCOUNT'] = os.getenv('GOOGLE_PLUS_ACCOUNT')
# kwargs['SKYPE_ACCOUNT'] = os.getenv('SKYPE_ACCOUNT')